### ISSUE TITLE
Separate/Add "country of residence" to the plugin menu

### ISSUE THREAD

**Issue by Neverends4** [wiiu-env/region_free_plugin#24]
Hi there, 

Thanks for the Aroma and this plugin, which both work like a charm on my Japanese Wii U. But now I encountered a small issue: With the region free plugin built in the latest Aroma Beta-16 (also tried latest nightly here), when running Wii Fit U, the measurement unit is always showed in imperial, see pic below:
![imperial](https://github.com/wiiu-env/region_free_plugin/assets/60057527/9db8012f-9134-45bf-a41b-81e20d3fef46)

This is really annoying as I need to convert my height and weight into metric every time when doing daily body test. At first I thought this was because the US version, so I tried EU version, still the same. However I noticed that if I chose a language with its country using metric system, the unit displayed in the game will change to metric, e.g. I use the setting below (the combination is nonsense, jut an example and the game still runs...):
![Deutsch](https://github.com/wiiu-env/region_free_plugin/assets/60057527/caffa0d4-0442-4692-bc2c-3806884b634f)

You can see the game now displays in German, and uses metric units:
![metric](https://github.com/wiiu-env/region_free_plugin/assets/60057527/3a685943-e8ca-4da9-be43-1693d708a3b0)

I also googled a while and found out that if you change your country of residence to one using metric system, the game will use this setting and display accordingly. 

So my question is, can you separate the "language" and "country of residence" in the plugin setting menu? e.g. if I can choose Netherland as country of residence and English as language, I can play Wii Fit U more easily. 

This setting might be beneficial also to other games using this very setting running on Japanese Wii U, as Japanese firmware does not have the setting to change "country of residence". 
I am aware I can switch region completely using the recovery menu method, but that is too risky and need a Pi pico to work. Since we have already got your wonderful plugin, why not go a step further? 
Thank you and have a good day.

**Comment by Maschell** [comment]
Thanks for the feedback!

I had this implemented in the first release, but removed it for some reason. I can't remember exactly why. Maybe because I defaulted it to a specific country which what not very intuitive.

For the next release I'll try implement it as an optional option though!

**Comment by Neverends4** [comment]
Hi Maschell,

Thanks for the reply.

I understand you want keep the plugin and the whole Aroma env simple. I too think selecting dozens of regions by left and right is too time consuming.

Since the region of residence is not an option needing frequent change, maybe just let user to input a value of region code is faster? e.g. I want Netherland as my region, I just need to input the code 31. And you can restrict the valid condition of values to make the code robust.

Best,
Avin
________________________________

**Comment by Neverends4** [comment]
Hi Maschell,

Just found out that there is a config on SD for your plugin:
`\wiiu\environments\aroma\plugins\config`

And basically the region of residence option is exposed here in txt:

` "default_cntry_reg_eur": 110,`
` "default_cntry_reg_jpn": 1,`
` "default_cntry_reg_usa": 49,`


I believe the number 110 takes from Eshop country code right? Currently **region for Europe defaults to 110=United Kingdom**. I tried and confirmed **if changing this code to the country using metric system, like Netherlands(94), the units display in Wii Fit U WILL CHANGE accordingly!**

So if you decide not to add this option in the new version, then maybe adding a description for manually changing the code is enough. 

Again thanks for your fantastic plugin.
